### ISSUE TITLE
Cannot find module http-server

### ISSUE THREAD

**Issue by kleoken** [bward2/pacman-js#80]
OS: macOS Mojave 10.14.6

Steps to reproduce:
1. `npm install`
2. `gulp watch`
3. `npm run serve`

Result: 
```
npm run serve      21:01:40

> @ serve /Users/celo/Developer/pacman-js
> node .\node_modules\http-server\bin\http-server

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/Users/celo/Developer/pacman-js/.node_moduleshttp-serverbinhttp-server'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ serve: `node .\node_modules\http-server\bin\http-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/celo/.npm/_logs/2020-08-27T01_01_42_495Z-debug.log
```

I was able to get around this by typing out the npm command in the console and changing the double backslashes to single forward slashes. Like so:
`> node ./node_modules/http-server/bin/http-server`

macOS doesn't like the backslashes in the console :)

**Comment by bward2** [comment]
@kleoken Thanks for pointing this out! I'll try to find a way that works on both Windows and macOS tonight.

If you've got any ideas, I'm all ears!

**Comment by bward2** [comment]
@kleoken Fixed! Looks like forward slashes work on Windows 10 now as well. I've updated master branch accordingly.

Thanks!
